addons:
  apt:
    packages:
    - python-pygments
install:
- rm -rf public || exit 0
script:
- chmod +x ./build.sh
- "./build.sh"
before_deploy:
- openssl aes-256-cbc -K $encrypted_05e3463f8f2c_key -iv $encrypted_05e3463f8f2c_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy/id_rsa
- ssh-add ./deploy/id_rsa
deploy:
  # deploy to stage on all commits
  - provider: script
    skip_cleanup: true
    script: rsync -rav --delete $TRAVIS_BUILD_DIR/dist/ cyrberus@stage.maniacallabs.com:/home/cyrberus/stage.maniacallabs.com/
    on:
      all_branches: true
  - provider: pages
    fqdn: ManiacalLabs.com
    skip_cleanup: true
    local_dir: public
    github_token: "$GITHUB_TOKEN"
    on:
      branch: master

