git:
  depth: 1
addons:
  apt:
    packages:
    - python-pygments
install:
- rm -rf public || exit 0
before_script:
- openssl aes-256-cbc -K $encrypted_05e3463f8f2c_key -iv $encrypted_05e3463f8f2c_iv
  -in id_rsa.enc -out ./id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 ./id_rsa
- ssh-add ./id_rsa
script:
- chmod +x ./build.sh
- "./build.sh"
addons:
  ssh_known_hosts:
  - stage.maniacallabs.com
deploy:
  - provider: pages
    fqdn: ManiacalLabs.com
    skip_cleanup: true
    local_dir: public
    github_token: "$GITHUB_TOKEN"
    on:
      branch: master

