baseurl: https://ManiacalLabs.github.io/ManiacalLabs.com
languageCode: en-us
title: Maniacal Labs
# author: Maniacal Labs, LLC
theme: osprey

# frontmatter:
#   date: "lastmod"

# enableGitInfo: true
enableRobotsTXT: true
metaDataFormat: yaml

paginate: 10
paginatePath: page

# disqusShortname: your_disqus_shortname
permalinks:
  posts: '/:year/:month/:slug/'
  code: '/:slug/'
taxonomies:
  tag: tags
  topic: topics

summaryLength: 30
enableEmoji: true
pygmentsCodeFences: true

# disqusShortname: "" #Disqus shortname
# googleAnalytics: ""

author:
  name: Maniacal Labs
  github: ManiacalLabs
  twitter: ManiacalLabs
# params:
#   tagline: No good can come of this

privacy:
  disqus:
    disable: false
  googleAnalytics:
    anonymizeIP: true
    disable: false
    respectDoNotTrack: true
    useSessionStorage: true
  instagram:
    disable: true
    simple: false
  speakerDeck:
    disable: true
  twitter:
    disable: false
    enableDNT: false
  vimeo:
    disable: false
  youtube:
    disable: false
    privacyEnhanced: true

config: config.yaml
canonifyURLS: true
googleAnalytics: ''
# disqusShortname:
disableKinds:
  - taxonomy
  - taxonomyTerm
Params:
  tagline: No good can come of this
  author: Maniacla Labs
  description: 'Makers of unique electronic and open source things'
  logoBig: /images/LogoWithBeaker.png
  logoSmall: /images/LogoWithBeaker.png
  favicon: favicon.ico
  opengraphImage: /images/LogoWithBeaker.png
  twitter: ManiacalLabs
  github: ManiacalLabs
  facebook: ManiacalLabs
  email: contact@maniacallabs.com
  # googleTagManager: ''
  highlightJS: true
  copyright: true
  credit: true
  customCSS: true
  cacheBustCSS: false
  cacheBustJS: false
  ajaxFormspree: true
menu:
  main:
    - name: About
      url: '/#about'
      weight: 1
    - name: Work
      url: '/#work'
      weight: 2
    - name: Blog
      url: '/#blog'
      weight: 3
    - name: Contact
      url: '/#contact'
      weight: 4

