baseurl: https://ManiacalLabs.com
languageCode: en-us
title: Maniacal Labs
description: No Good Can Come of This
permalinks:
  posts: '/:year/:month/:day/:slug/'
  code: '/:slug/'
theme: kube
disqusShortname: maniacallabs
googleAnalytics: UA-41371810-1
canonifyURLS: true
enableRobotsTXT: true

Paginate: 10
Params:
  logo: /images/logo-beaker.png
  RSSLink: /feed/
  author: Maniacal Labs
  github: ManiacalLabs
  facebook: ManiacalLabs
  twitter: ManiacalLabs
  instagram: ManiacalLabs
  email: contact@maniacallabs.com
menu:
  main:
    - name: Products
      weight: 10
      url: /products/
    - name: Blog
      weight: 20
      url: /posts/
    - name: Projects
      weight: 30
      url: /projects/
    # - name: Build Log
    #   weight: 35
    #   url: /buildlog/
    - name: About
      weight: 40
      url: /about/
    - name: Contact
      weight: 50
      url: /contact/
