baseurl: https://ManiacalLabs.github.io/ManiacalLabs.com
languageCode: en-us
title: Maniacal Labs
description: >-
  Kube is a professional  and a responsive Hugo theme for developers and
  designers that offers a documentation section mixed with a landing page and a
  blog
permalinks:
  posts: '/:year/:month/:day/:slug/'
  code: '/:slug/'
theme: kube
# disqusShortname: username
# googleAnalytics: ''
canonifyURLS: true

Paginate: 10
Params:
  RSSLink: /feed/
  author: Maniacal Labs
  github: ManiacalLabs
  twitter: ManiacalLabs
  instagram: ManiacalLabs
  email: contact@maniacallabs.com
menu:
  main:
    # - name: Docs
    #   weight: -100
    #   url: /docs/
    - name: Projects
      weight: -100
      url: /projects/
    - name: Products
      weight: -100
      url: /products/
    - name: Blog
      weight: -100
      url: /posts/
    - name: About
      weight: -100
      url: /About/
